// Code generated by MockGen. DO NOT EDIT.
// Source: total_stock.go
//
// Generated by this command:
//
//	mockgen -source=total_stock.go -destination=../../../../../test/mocks/total-stock/infra/api/groups/total_stock_mock.go -package mock_total_stock_groups
//

// Package mock_total_stock_groups is a generated GoMock package.
package mock_total_stock_groups
