package com.imaginamos.farmatodo.model.util;

import com.imaginamos.farmatodo.model.environment.Enviroment;
import com.imaginamos.farmatodo.model.environment.Production;

import java.io.IOException;
import java.net.HttpURLConnection; 
import java.net.URL;

public class URLConnections {

	/**
	 * Cambie aqui el ambiente al que desea apuntar [DEV], [PROD], [TEST], [STAGING]
	 * */
	//Develop
	//public static final Enviroment ENVIROMENT = Development.getInstance();
	//Sandbox
	//public static final Enviroment ENVIROMENT = Sandbox.getInstance();
	//Production
	public static final Enviroment ENVIROMENT = Production.getInstance();
	//QA
//	public static final Enviroment ENVIROMENT = QA.getInstance();
//	Contingency
//	public static final Enviroment ENVIROMENT = Contingency.getInstance();

// 	STAGING
//	public static final Enviroment ENVIROMENT = Staging.getInstance();

	/** ips */
	public static final String ENVIROMENT_NAME           = ENVIROMENT.ENVIROMENT_NAME;
	private static final String IP_BASE 			     = ENVIROMENT.IP_BASE;
	public static final String BACKEND_CORE_30_HOST_BASE = ENVIROMENT.BACKEND_CORE_30_HOST_BASE;
	public static final String IP_BASE_MONITOR           = ENVIROMENT.IP_BASE_MONITOR;
	public static final String URL_BASE                  = IP_BASE; /** Retrofit: */
	public static final String URL_BASE_CLOUD_FUNCTIONS  = "http://us-central1-stunning-base-164402.cloudfunctions.net/";
	public static final String URL_BASE_CLOUD_FUNCTIONSV2= "https://us-central1-stunning-base-164402.cloudfunctions.net/";
	public static final String URL_BASE_BRAZE_FLASK      = "http://10.193.0.49:4433";


	//public static final String BACKEND_CORE_30_HOST_BASE = ENVIROMENT.BACKEND_CORE_30_HOST_BASE;

	/** Endpoints Backend 3.0: */
//	public static final String URL_PREVALIDATE_DEL_ADDRESS_BC_30    = BACKEND_CORE_30_HOST_BASE+ Enviroment.PREVALIDATE_DELETE_ADDRES;
	public static final String URL_PREVALIDATE_DEL_CREDITCARD_BC_30 = BACKEND_CORE_30_HOST_BASE + Enviroment.URL_PREVALIDATE_DEL_CREDITCARD_BC_30;
	public static final String URL_GET_DISCOUNT_BY_CUSTOMER_BC_30   = ENVIROMENT.BACKEND_CORE_30_HOST_BASE + Enviroment.URL_GET_DISCOUNT_BY_CUSTOMER_BC_30;
	public static final String URL_SEND_CUSTOMER_ATOM               = ENVIROMENT.IP_BASE + Enviroment.URL_SEND_CUSTOMER_ATOM;

	/** OMS **/
	public static final String URL_OMS_CREATE_ORDER   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_CREATE_ORDER;

	public static final String URL_OMS_CREATE_ORDER_V2   				= ENVIROMENT.OMS_DIRECT + Enviroment.URL_OMS_CREATE_ORDER;
	public static final String URL_OMS_EDIT_ORDERS   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_EDIT_ORDERS;
	public static final String URL_GET_ORDER_INFO                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_ORDER_INFO;
	public static final String URL_OMS_OPTIMAL_ROUTE_CHECKOUT  		= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_OPTIMAL_ROUTE_CHECKOUT;
	public static final String URL_ROUTER_OPTIMAL_ROUTE_POP_UP  		= ENVIROMENT.API_GATEWAY + Enviroment.URL_ROUTER_OPTIMAL_ROUTE_POP_UP;
	public static final String URL_OMS_GET_ORDER_STOPS   	        = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_STOPS;
	public static final String URL_OMS_GET_UNBILLED_ITEMS_BY_ORDER  = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_UNBILLED_ITEMS_BY_ORDER;
	public static final String URL_OMS_GET_ORDER_COORDINATES        = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_COORDINATES;
	//public static final String URL_OMS_CHARGE_ORDER    	            = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_CHARGE_ORDER;
	public static final String URL_OMS_CHARGE_ORDER    	            = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_CHARGE_ORDER;
	public static final String URL_OMS_VALIDATE_FREE_DELIVERY       = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_VALIDATE_FREE_DELIVERY;

	public static final String URL_OMS_RELATION_ORDER_PRIME       = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_RELATION_ORDER_PRIME;

	public static final String URL_OMS_GET_ORDER_SUMMARY_BY_ORDER_ID= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_SUMMARY_BY_ORDER_ID;

	public static final String URL_OMS_GET_LAST_STATUS_ORDER_PROVIDER = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_LAST_STATUS_ORDER_PROVIDER;
	public static final String URL_OMS_GET_ORDER_INFO	    	   	= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_INFO;
	public static final String URL_OMS_GET_RATINGS    	            = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_RATINGS;
	public static final String URL_OMS_READ_ORDER                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_READ_ORDER;
	public static final String URL_EDIT_ORDERS_COURIER              = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_EDIT_ORDER_FROM_COURIER;

	public static final String URL_OMS_ORDER_QUALIFY                = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_QUALIFY;
	public static final String URL_OMS_PUT_ORDER_STATUS_UPDATE      = ENVIROMENT.API_GATEWAY  + Enviroment.URL_OMS_PUT_ORDER_STATUS_UPDATE;
	public static final String URL_OMS_PUT_ORDER_PICKING_DATE      = ENVIROMENT.API_GATEWAY  + Enviroment.URL_OMS_PUT_ORDER_PICKING_DATE;
	public static final String URL_OMS_POST_ORDER_PROVIDER_STATUS_UPDATE = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_POST_ORDER_PROVIDER_STATUS_UPDATE;
	public static final String URL_OMS_GET_ORDER_PROVIDER 			= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_PROVIDER;

	public static final String URL_OMS_GET_COURIER_ALL              = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_COURIER_ALL;
	public static final String URL_OMS_CANCEL_ORDER_TO_COURIER      = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_CANCEL_ORDER_TO_COURIER;

	public static final String URL_OMS_PUT_ORDER_PAYMENT_METHOD     = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_PUT_ORDER_PAYMENT_METHOD;

	public static final String URL_OMS_ORDER_SUBSCRIPTION_CENDIS_MAIL 	= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_SUBSCRIPTION_CENDIS_MAIL;
	public static final String URL_OMS_GET_ACTIVE_ORDER			 	= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ACTIVE_ORDER;
	public static final String URL_OMS_GET_ORDER_QUANTITY_ITEM	 	= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_QUANTITY_ITEM;
	public static final String URL_OMS_GET_ORDER_INFO_ITEM	 	= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_ORDER_INFO_ITEM;
	public static final String URL_OMS_ORDER_CANCEL	 				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_CANCEL;
	public static final String URL_OMS_ORDER_CANCEL_RX	 				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_CANCEL_RX;
	public static final String URL_OMS_ORDER_INFO                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_INFO;
	public static final String URL_OMS_ORDER_INFO_AMPL              = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_INFO_AMPL;
	public static final String URL_OMS_ORDER_INFO_AMPLITUDE_BRAZE              = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_ORDER_INFO_AMPLITUDE_BRAZE;
	public static final String URL_OMS_VALIDATE_COUPON			  = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_VALIDATE_COUPON;
	public static final String URL_OMS_VALID_COUPON                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_VALID_COUPON;
	public static final String URL_OMS_GET_TOKEN_FIREBASE                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_TOKEN_FIREBASE;
	public static final String URL_OMS_GET_COURIER_UUID               = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_COURIER_UUID;
	public static final String URL_VALIDATE_ORDER_STATUS_ORACLE      = ENVIROMENT.API_GATEWAY + Enviroment.URL_VALIDATE_ORDER_STATUS;
	public static final String URL_OMS_GET_ORDER_DELIVERY      = ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_GET_DELIVERY;
	/** BRAZE **/
	public static final String URL_SEND_EMAIL_BRAZE =    			ENVIROMENT.API_GATEWAY + Enviroment.URL_SEND_EMAIL_BRAZE;
	public static final String URL_UPLOAD_STRATUM_BRAZE             = ENVIROMENT.API_GATEWAY + Enviroment.URL_UPLOAD_STRATUM_BRAZE;
	public static final String URL_ADD_NON_STOCK_ITEM_BRAZE             = ENVIROMENT.API_GATEWAY + Enviroment.URL_ADD_NON_STOCK_ITEM_BRAZE;
	public static final String URL_UPDATE_NOTIFICATION_PREFERENCES_BRAZE = ENVIROMENT.API_GATEWAY + Enviroment.URL_UPDATE_NOTIFICATION_PREFERENCES_BRAZE;
	public static final String URL_SEND_PUSH_NOTIFICATION_BRAZE = ENVIROMENT.API_GATEWAY + Enviroment.URL_SEND_PUSH_NOTIFICATION_BRAZE;
	public static final String URL_UPDATE_USER_PROFILE_BRAZE = ENVIROMENT.API_GATEWAY + Enviroment.URL_UPDATE_USER_PROFILE_BRAZE;
	public static final String URL_SEND_EVENT_BRAZE = ENVIROMENT.API_GATEWAY + Enviroment.URL_SEND_EVENT_BRAZE;

	public static final String URL_POST_SAVING_DATASTORE = ENVIROMENT.API_GATEWAY + Enviroment.URL_POST_SAVING_DATASTORE;

	/** Prime **/
	public static final String URL_UPDATE_ATOM				= ENVIROMENT.API_GATEWAY + Enviroment.URL_UPDATE_ATOM;
	public static final String URL_OMS__GET_ANTIFRAUDE_VALIDATE   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS__GET_ANTIFRAUDE_VALIDATE;
	public static final String URL_OMS_POST_MICRO_CHARGE_GENERATE   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_POST_MICRO_CHARGE_GENERATE;
	public static final String URL_OMS_POST_MICRO_CHARGE_VALIDATE   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_POST_MICRO_CHARGE_VALIDATE;

	public static final String URL_CRM_SUBSCRIBE_PRIME_FREE_DAYS = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_SUBSCRIBE_PRIME_FREE_DAYS;
	/** CRM **/
    public static final String URL_CRM_GET_CUSTOMER_PHOTOS          = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_PHOTOS;
	public static final String URL_CRM_GET_CUSTOMER_BY_ADDRESS   	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_BY_ADDRESS;
	public static final String URL_CRM_GET_CUSTOMER_BY_EMAIL   		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_BY_EMAIL;
	public static final String URL_CRM_GET_CUSTOMER_BY_EMAIL_LOWER_CASE  = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_BY_EMAIL_LOWER_CASE;
	public static final String URL_CRM_GET_CUSTOMER_EMAIL_VALIDATE  = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_EMAIL_VALIDATE;
	public static final String URL_CRM_GET_CUSTOMER_EMAIL_VALIDATE_CALL  = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_EMAIL_VALIDATE_CALL;
	public static final String URL_CRM_GET_CUSTOMER_DOCUMENT_NUMBER_VALIDATE  = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_DOCUMENT_NUMBER_VALIDATE;
	public static final String URL_CRM_GET_CUSTOMER_CREDIT_CARD     = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_CREDIT_CARD;
	public static final String URL_CRM_POST_GET_ALL_CUSTOMERS		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_ALL_CUSTOMERS;
	public static final String URL_PREVALIDATE_DELETE_CREDIT_CARD   = ENVIROMENT.API_GATEWAY + Enviroment.PREVALIDATE_DELETE_CREDIT_CARD;
	public static final String URL_VALIDATE_ADDRESS_BCK3			= ENVIROMENT.API_GATEWAY + Enviroment.VALIDATE_ADDRESS;
	public static final String URL_UPDATE_CUSTOMER_ADDRESS			= ENVIROMENT.API_GATEWAY + Enviroment.UPDATE_CUSTOMER_ADDRESS;
	public static final String URL_CRM_CUSTOMER_ONLY          		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_ONLY;

	public static final String URL_OMS_MESSENGER_NAME         		= ENVIROMENT.API_GATEWAY + Enviroment.URL_OMS_MESSENGER_NAME;
	public static final String URL_CRM_GET_ADDRESS_BY_CUSTOMER      = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_ADDRESS_BY_CUSTOMER;
	public static final String URL_CRM_CREATE_CUSTOMER		        = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CREATE_CUSTOMER;
	public static final String URL_CRM_GET_CUSTOMER_CALL	        = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_CALL;
	public static final String URL_CRM_CREATE_CUSTOMER_ADDRESS	    = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_ADDRESS;
	public static final String URL_CRM_UPDATE_CUSTOMER_ADDRESS_DEFAULT	    = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_UPDATE_CUSTOMER_ADDRESS_DEFAULT;
	public static final String URL_CRM_PUT_CUSTOMER_ADDRESS	   		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_ADDRESS;
	public static final String URL_CRM_CREATE_BASIC_CUSTOMER        = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER;
	public static final String URL_CRM_GET_CUSTOMER        			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER;
	public static final String URL_CRM_VALIDATE_CUSTOMER        	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_VALIDATE_CUSTOMER;
	public static final String URL_CRM_IS_SAME_PASSWORD				= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_IS_SAME_PASSWORD;

	public static final String URL_CRM_PUT_CUSTOMER        			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER;
	public static final String URL_CRM_CUSTOMER_LOGIN_EMAIL        	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_LOGIN_EMAIL;
	public static final String URL_CRM_CUSTOMER_LOGIN_FACEBOOK      = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_LOGIN_FACEBOOK;
	public static final String URL_CRM_CUSTOMER_LOGIN_GOOGLE        = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_LOGIN_GOOGLE;
	public static final String URL_CRM_VALIDATE_CUSTOMER_GOOGLE        = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_VALIDATE_CUSTOMER_GOOGLE;
	public static final String URL_CRM_POST_CUSTOMER_CREDIT_CARD    = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_CUSTOMER_CREDIT_CARD;
	public static final String URL_CRM_DELETE_CUSTOMER_ADDRESS_BY_ID= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_DELETE_CUSTOMER_ADDRESS_BY_ID;
	public static final String URL_CRM_DELETE_CREDIT_CARD_BY_ID_AND_CUSTOMER_ID= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_DELETE_CREDIT_CARD_BY_ID_AND_CUSTOMER_ID;
	public static final String URL_CRM_GET_CREDIT_CARD_TOKEN_BY_CUSTOMER_ID_AND_GATEWAY= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CREDIT_CARD_TOKEN_BY_CUSTOMER_ID_AND_GATEWAY;
	public static final String URL_CRM_GET_CREDIT_CARD_GATEWAY_ACTIVE= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CREDIT_CARD_GATEWAY_ACTIVE;



	public static final String URL_CRM_POST_CUSTOMER_CREDIT_CARD_DEF= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_CUSTOMER_CREDIT_CARD_DEF;
	public static final String URL_CRM_UPDATE_EMAIL                 = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_UPDATE_EMAIL;
	public static final String URL_CRM_CUSTOMER_LOGIN_DOCUMENT          = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_LOGIN_DOCUMENT;
	public static final String URL_CRM_CUSTOMER_FRAUD               = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_FRAUD;
	public static final String URL_CRM_CUSTOMER_CREDIT_CARD_FRAUD   = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_CUSTOMER_CREDIT_CARD_FRAUD;


	public static final String URL_CRM_POST_LIFEMILES_CUSTOMER		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_LIFEMILES_CUSTOMER;
	public static final String URL_CRM_POST_LIFEMILES_CALCULATE		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_LIFEMILES_CALCULATE;
	public static final String URL_CRM_POST_LIFEMILES_NUMBER		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_LIFEMILES_NUMBER;
	public static final String URL_CRM_PUT_LIFEMILES_INACTIVE		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_PUT_LIFEMILES_INACTIVE;

	public static final String URL_CRM_RESET_PASSWORD				= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_RESET_PASSWORD;
	public static final String URL_CRM_PASSWORD_CHANGE              = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_PUT_CUSTOMER_PASSWORD_CHANGE;
	public static final String URL_CRM_PASSWORD_CHANGEV2            = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_PUT_CUSTOMER_PASSWORD_CHANGEV2;

	public static final String URL_CRM_POST_ORIGIN_BY_EMAIL			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_ORIGIN_BY_EMAIL;
	public static final String URL_CRM_POST_ORIGIN_BY_PHONE			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_ORIGIN_BY_PHONE;
	public static final String URL_CRM_POST_ORIGIN_BY_UID			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_ORIGIN_BY_UID;

	public static final String URL_CRM_GET_CUSTOMER_BY_DOCUMENT		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_BY_DOCUMENT;
	public static final String URL_CRM_GET_CUSTOMER_DATA_CREDIT_CARD	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_PRIME_CART;

	public static final String URL_CRM_GET_CUSTOMER_PRIME	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_CUSTOMER_PRIME;
	public static final String URL_CRM_GET_IS_CUSTOMER_PRIME			= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_IS_CUSTOMER_PRIME;
	public static final String URL_CRM_PUT_SAVING_PRIME		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_PUT_SAVING_PRIME;
	public static final String URL_CRM_GET_SUGGESTED				= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_SUGGESTED;

	public static final String URL_CRM_POST_CUSTOMER_MONITOR		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_POST_CUSTOMER_MONITOR;
	public static final String URL_CRM_DELETE_LOGIC_CUSTOMER		= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_DELETE_LOGIC_CUSTOMER;

	public static final String URL_CRM_GET_DATA_CUSTOMER_LOGIN	    = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_DATA_CUSTOMER_LOGIN;
	public static final String URL_CRM_SEND_MAIL_CODE_LOGIN		    = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_SEND_MAIL_CODE_LOGIN;
	public static final String URL_CRM_GET_PHONE_NUMBER		    	= ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_GET_PHONE_NUMBER;
	public static final String URL_CRM_FIND_CUSTOMER_DANE_CODE_CITY_BY_ID_CITY = ENVIROMENT.API_GATEWAY + Enviroment.URL_CRM_FIND_CUSTOMER_DANE_CODE_CITY_BY_ID_CITY;
	//  BACKEND 2
	public static final String URL_BCK2_CLICK_EMAIL_UPDATE			= ENVIROMENT.API_GATEWAY + Enviroment.URL_BCK2_CLICK_EMAIL_UPDATE;

	/** ANTIFRAUD **/
	public static final String URL_GET_CUSTOMER_BY_PHONE   			= ENVIROMENT.ANTIFRAUD + Enviroment.URL_GET_CUSTOMER_BY_PHONE;

	/** DATA_FOUNDATION **/
	public static final String URL_DTF_POST_VALIDATE_STOCK			= ENVIROMENT.DTF_DIRECT + Enviroment.URL_DTF_POST_VALIDATE_STOCK;
	public static final String URL_DTF_GET_BANNERS          		= ENVIROMENT.API_GATEWAY + Enviroment.URL_DTF_GET_BANNERS;
	public static final String URL_DTF_ORDER_PROVIDER_STOCK_UPDATE = ENVIROMENT.API_GATEWAY + Enviroment.URL_DTF_ORDER_PROVIDER_STOCK_UPDATE;
	public static final String URL_PAYMENT_METHODS_ACTIVE           = ENVIROMENT.API_GATEWAY + Enviroment.URL_PAYMENT_METHODS_ACTIVE;

	public static final String URL_GET_STORE_ACTIVE           		= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_STORE_ACTIVE;
	public static final String URL_GET_CITY_ACTIVE           		= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_CITY_ACTIVE;
	public static final String URL_GET_ITEM_BY_ID           		= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_ITEM_BY_ID;
	public static final String URL_POST_GET_ITEMS           		= ENVIROMENT.API_GATEWAY + Enviroment.URL_POST_GET_ITEMS;
	public static final String URL_POST_ITEM_START           		= ENVIROMENT.API_GATEWAY + Enviroment.URL_POST_ITEM_START;
	public static final String URL_POST_ITEM_START_DONE        		= ENVIROMENT.API_GATEWAY + Enviroment.URL_POST_ITEM_START_DONE;
	public static final String URL_GET_ITEM_BARCODE        			= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_ITEM_BARCODE;
	public static final String URL_GET_CLASSIFICATION_ACTIVE   		= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_CLASSIFICATION_ACTIVE;
	public static final String URL_GET_CROSS_SALES   				= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_CROSS_SALES;
	public static final String URL_GET_HIGHLIGHT   					= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_HIGHLIGHT;
	public static final String URL_GET_OFFER_ACTIVE  				= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_OFFER_ACTIVE;
	public static final String URL_GET_CLOSER_COORDINATES 			= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_CLOSER_COORDINATES;
	public static final String URL_GET_SHORTCUT_ACTIVE 				= ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_SHORTCUT_ACTIVE;
	public static final String URL_POST_CREATE_PROVIDER				= ENVIROMENT.API_GATEWAY + Enviroment.URL_POST_CREATE_PROVIDER;
	public static final String URL_GET_ACTIVE_PSE				    = ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_ACTIVE_PSE;
    public static final String URL_CREATE_ITEM_ALGOLIA_SAG          = ENVIROMENT.API_GATEWAY + Enviroment.URL_GET_CREATE_PRODUCT_SAG;

    /** DATAFOUNDATION **/
	public static final String URL_PAYMENT_METHODSV2		         = ENVIROMENT.API_GATEWAY + Enviroment.URL_PAYMENT_METHODS_V2;



	/** AUTH **/
	public static final String URL_PUT_AUTH_BY_CLIENT_ID_SECRET		= ENVIROMENT.API_GATEWAY + Enviroment.URL_PUT_AUTH_BY_CLIENT_ID_SECRET;

	/**  CMS  **/
	public static final String URL_BASE_BANNERS_CMS					= ENVIROMENT.CMS_DIRECT;
	public static final String URL_BANNERS_CMS						= ENVIROMENT.API_GATEWAY + Enviroment.URL_CMS_BANNERS;
	public static final String URL_BANNERS_CMS_V2					= ENVIROMENT.API_GATEWAY + Enviroment.URL_CMS_BANNERS_V2;
	public static final String URL_BANNERS_MIN_LEFT_CMS_V2 = ENVIROMENT.API_GATEWAY + Enviroment.URL_BANNERS_MIN_LEFT_CMS_V2;


	/** Shopping Cart **/
	public static final String URL_SHOPPING_PRICE_DELIVERY_ORDER = ENVIROMENT.SHOPPING_DIRECT + Enviroment.URL_SHOPPING_PRICE_DELIVERY_ORDER;

	public static final String URL_SHOPPING_PRICE_DELIVERY_ORDER_V2 = ENVIROMENT.SHOPPING_DIRECT_FAIL_OVER + Enviroment.URL_SHOPPING_PRICE_DELIVERY_ORDER;

	public static final String URL_SHOPPING_CART_STORE_STOCK = ENVIROMENT.SHOPPING_DIRECT + Enviroment.URL_ENDPOINT_STORE_STOCK;

	/** Firebase */
	public static final String URL_PASSWORD_FIREBASE = ENVIROMENT.URL_PASSWORD_FIREBASE;
	public static final String URL_GET_USER_FIREBASE = ENVIROMENT.URL_GET_USER_FIREBASE;
	public static final String URL_AMPLITUDE_SESSION_ID = ENVIROMENT.API_GATEWAY + Enviroment.URL_AMPLITUDE_SESSION;

	public static final String URL_FIREBASE_GET_CODE_LOGIN = ENVIROMENT.API_GATEWAY + Enviroment.URL_FIREBASE_GET_CODE_LOGIN;

	public static final String URL_FIREBASE_ADD_CODE_LOGIN = ENVIROMENT.API_GATEWAY + Enviroment.URL_FIREBASE_ADD_CODE_LOGIN;

	public static final String URL_FIREBASE_DELETE_CODE_LOGIN = ENVIROMENT.API_GATEWAY + Enviroment.URL_FIREBASE_DELETE_CODE_LOGIN;

	/** PAUY */
	public static final String PAYU_API_LOGIN = ENVIROMENT.PAYU_API_LOGIN;
	public static final String PAYU_API_KEY   = ENVIROMENT.PAYU_API_KEY;
	public static final String URL_PAYU       = ENVIROMENT.URL_PAYU;

	/** Main Store ID */
	public static final String MAIN_ID_STORE = ENVIROMENT.MAIN_ID_STORE;

	public static final int NATIONAL_ID_STORE = 1000;
	public static final int ENVIALOYA_ID_STORE = 1001;

	/** NESTUtilities */
	public static final String GET_UUID_BRAZE       			= ENVIROMENT.API_GATEWAY + Enviroment.URL_BRAZE_GET_UUID;
	public static final String GET_UUID_BRAZE_CREATE_USER       = ENVIROMENT.API_GATEWAY + Enviroment.URL_BRAZE_CREATE_USER_BY_EMAIL;
	public static final String URL_LOGINBYUID                   = ENVIROMENT.API_GATEWAY + Enviroment.URL_LOGINBYUID;
	public static final String URL_AMPLITUDE_PRODUCT_BOUGHT      = ENVIROMENT.API_GATEWAY + Enviroment.URL_AMPLITUDE_PRODUCT_BOUGHT;
	public static final String URL_AMPLITUDE_ORDER_COMPLETE      = ENVIROMENT.API_GATEWAY + Enviroment.URL_AMPLITUDE_ORDER_COMPLETE;
	public static final String URL_TRENDING_ITEMS = ENVIROMENT.API_GATEWAY + Enviroment.URL_TRENDING_ITEMS;

	public static final String URL_AMPLITUDE_ORDER_COMPLETE_V2 = ENVIROMENT.API_GATEWAY + Enviroment.URL_AMPLITUDE_ORDER_COMPLETE_V2;

	/** Flask - RMS **/
	public static final String URL_RMS_BUSINESS_ITEM = URL_BASE_BRAZE_FLASK + Enviroment.URL_RMS_BUSINESS_ITEM;
	public static final String URL_RMS_BUSINESS_ORDER = URL_BASE_BRAZE_FLASK + Enviroment.URL_RMS_BUSINESS_ORDER;

	/**
	 * REDIS
	 */
	public static final String REDIS_DB_IP  			  = ENVIROMENT.REDIS_DB_IP;
	public static final Integer REDIS_DB_PORT  			  = ENVIROMENT.REDIS_DB_PORT;

	/** GEOCODER */
	public static final String GEOCODER_LUPAP_PLACEID = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_LUPAP_PLACEID;
	public static final String GEOCODER_LUPAP_PLACEID_V2 = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_LUPAP_PLACEID_V2;
	public final static String GEOCODER = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER;
	public final static String GEOCODER_V2 = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_V2;

	public final static String GEOCODER_BY_LUPAP_SERVI = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_BY_LUPAP_SERVI;

	public final static String GEO_ZONE_BY_LAT_LNG = ENVIROMENT.NEST_UTILITIES_DIRECT + ENVIROMENT.GEO_ZONE_BY_LAT_LNG;
	public final static String GEOCODER_INVERSO = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_INVERSO;
	public final static String GEOCODER_INVERSO_V2 = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_INVERSO_V2;

	public final static String GEOCODER_INVERSO_V3 = ENVIROMENT.API_GATEWAY + ENVIROMENT.GEOCODER_INVERSO_V3;
	public final static String AUTOCOMPLETE = ENVIROMENT.API_GATEWAY + ENVIROMENT.AUTOCOMPLETE;

	public final static String ADD_DELIVERY_ORDER_ITEM_ASYNC =  ENVIROMENT.API_GATEWAY + Enviroment.URL_ADD_DELIVERY_ORDER_ITEM_ASYNC;

	/** Algolia: */

	public static final String ALGOLIA_MESSAGE_CONFIG_CREATE_ORDER     = ENVIROMENT.ALGOLIA_MESSAGE_CONFIG_CREATE_ORDER;
	public static final String ALGOLIA_PHONE_NUMBERS_FOR_ALERT        = "PHONE.NUMBERS.FOR.ALERT";
	public static final String ALGOLIA_PHONE_NUMBERS_FOR_ALERT_OMS        = "PHONE.NUMBERS.FOR.ALERT.ERROR.OMS";
	public static final String ALGOLIA_PHONE_NUMBERS_FOR_ALERT_PAYU        = "PHONE.NUMBERS.FOR.ALERT.ERROR.PAYU";
	public static final String ALGOLIA_INDEX_ALERTS_OPERATION_CONFIG  = "alerts_operation_config";
	public static final String ALGOLIA_HIGHLIGHTS_OFFERS	    	  = "highlights_offers";
	public static final String ALGOLIA_PRODUCTS     				  = ENVIROMENT.ALGOLIA_PRODUCTS;
	public static final String ALGOLIA_BROWSE_HISTORY     		      = "browse_history_users";
	public static final String ALGOLIA_CONFIG_TIMEOUT 				  = "TIME.OUT.ORDER";
	public static final String ALGOLIA_SUBTRACT_STOCK_CONFIG 		  = "SUBTRACT.STOCK.CONFIG";
	public static final String ALGOLIA_LOAD_DATA_AMPLITUDE            = "LOAD.DATA.AMPLITUDE";
	public static final String ALGOLIA_ASYNC_AMPLITUDE           	  = "ASYNC.DATA.AMPLITUDE";
	public static final String ALGOLIA_CATEGORY_PHOTO 				  = "prod_category_photo";
	public static final String ALGOLIA_CATEGORIES_SEO 				  = "categories_seo";
	public static final String ALGOLIA_BANNERS 						  = "prod_banner";
	public static final String ALGOLIA_APP_ID       				  = ENVIROMENT.ALGOLIA_APP_ID;
	public static final String ALGOLIA_COUPON_POPUP       			  = ENVIROMENT.ALGOLIA_COUPON_POPUP;
	public static final String ALGOLIA_API_KEY      				  = ENVIROMENT.ALGOLIA_API_KEY;
	public static final String ALGOLIA_STORE_CONFIG 				  = ENVIROMENT.ALGOLIA_STORE_CONFIG;
	public static final String ALGOLIA_HOLIDAYS     				  = ENVIROMENT.ALGOLIA_HOLIDAYS;
	public static final String ALGOLIA_INDEX_PROPERTIES  			  = ENVIROMENT.ALGOLIA_INDEX_PROPERTIES;
	public static final String ALGOLIA_SUBSCRIBE_AND_SAVE_CONFIG_INDEX  			  = ENVIROMENT.ALGOLIA_SUBSCRIBE_AND_SAVE_CONFIG_INDEX;
	public static final String ALGOLIA_INDEX_ITEMS_SEO  			  = ENVIROMENT.ALGOLIA_INDEX_ITEMS_SEO;
	public static final String ALGOLIA_INDEX_CONFIG_SEO  			  = ENVIROMENT.ALGOLIA_INDEX_CONFIG_SEO;
	public static final String ALGOLIA_INDEX_PROD_VIDEO  			  = ENVIROMENT.ALGOLIA_INDEX_PROD_VIDEO;
	public static final String ALGOLIA_PROPERTIES                     = ENVIROMENT.ALGOLIA_PROPERTIES;
	public static final String ALGOLIA_INDEX_LANDING_PAGES            = ENVIROMENT.ALGOLIA_INDEX_LANDING_PAGES;
	public static final String ALGOLIA_PAYMENTMETHODS_DELIVERYTYPE    = ENVIROMENT.ALGOLIA_PAYMENTMETHODS_DELIVERYTYPE;
	public static final String ALGOILIA_DISTANCE_PROPERTIES           = ENVIROMENT.ALGOILIA_DISTANCE_PROPERTIES;
	public static final String ALGOLIA_AUTOCOMPLETE_GOOGLE_PROPERTIES = ENVIROMENT.ALGOLIA_AUTOCOMPLETE_GOOGLE_PROPERTIES;
	public static final String ALGOLIA_COURIER_SOCKET_ACTIVE          = ENVIROMENT.ALGOLIA_COURIER_SOCKET_ACTIVE;
	public static final String ALGOLIA_DEFAULT_STORES_BY_CITY         = ENVIROMENT.ALGOLIA_DEFAULT_STORES_BY_CITY;
	public static final String ALGOLIA_KEYWORDS_CONFIG         		  = ENVIROMENT.ALGOLIA_KEYWORDS_CONFIG;
	public static final String ALGOLIA_CONFIG_ADDRESS         		  = ENVIROMENT.ALGOLIA_CONFIG_ADDRESS;
	public static final String ALGOLIA_DEFAULT_STORES_BY_ID           = ENVIROMENT.ALGOLIA_DEFAULT_STORES_BY_ID;
	public static final String STORE_ID_DEFAULT_OPTICS                = ENVIROMENT.STORE_ID_DEFAULT_OPTICS;
	public static final String ALGOLIA_PAYMENTMETHODS_PROPERTIES      = ENVIROMENT.ALGOLIA_PAYMENTMETHODS_PROPERTIES;
	public static final String ALGOLIA_SUPPORT_NUMBERS                = ENVIROMENT.ALGOLIA_SUPPORT_NUMBERS;
	public static final String ALGOLIA_HTTPS_WEBSOCKET_URL            = ENVIROMENT.ALGOLIA_HTTPS_WEBSOCKET_URL;
	public static final String ALGOLIA_IMAGE_TRACKING                 = ENVIROMENT.ALGOLIA_IMAGE_TRACKING;
	public static final String ALGOLIA_HTTP_WEBSOCKET_URL             = ENVIROMENT.ALGOLIA_HTTP_WEBSOCKET_URL;
	public static final String ALGOLIA_INDEX_SORTED_HIGHLIGHT         = ENVIROMENT.ALGOLIA_INDEX_SORTED_HIGHLIGHT;
	public static final String ALGOLIA_STORES                         = "FTD.STORES";
	public static final String ALGOLIA_SAG_BASE_PROPERTIES            = ENVIROMENT.ALGOLIA_SAG_BASE_PROPERTIES;
    public static final String ALGOLIA_OPTIMAL_ROUTE_DISTANCES 		  = ENVIROMENT.ALGOLIA_OPTIMAL_ROUTE_DISTANCES;
	public static final String ALGOLIA_INDEX_ALL_CATEGORIES           = "prod_all_categories";
	public static final String ALGOLIA_INDEX_CROSS_SALES_AND_SUBSTITUTES = "cross_sales_and_suggested_items";
	public static final String ALGOLIA_SELF_CHECKOUT				  = "CONFIG_SELF_CHECKOUT";

	public static final String ALGOLIA_FACETS				  		  = "SS.FILTERS";

	public static final String ALGOLIA_WHATSAPP_CONFIG				  = "ALGOLIA_WHATSAPP_CONFIG";

	public static final String ALGOLIA_ITEM_FILTERS 				  = ENVIROMENT.ALGOLIA_FILTERS_PRODUCTS;
	public static final String ALGOLIA_CART_LABEL_DELIVERY_VALUE      = ENVIROMENT.ALGOLIA_CART_LABEL_DELIVERY_VALUE;
	public static final String ALGOLIA_DELIVERY_TIME_LABEL_CONFIG     = ENVIROMENT.ALGOLIA_DELIVERY_TIME_LABEL_CONFIG;
	public static final String ALGOLIA_DELIVERY_TIME_LABEL_TEMPLATE   = ENVIROMENT.ALGOLIA_DELIVERY_TIME_LABEL_TEMPLATE;
	public static final String ALGOLIA_DELIVERY_TIME_FOR_DELIVERY_TYPE= ENVIROMENT.ALGOLIA_DELIVERY_TIME_FOR_DELIVERY_TYPE;
	public static final String ALGOLIA_CREATE_ORDER_CONFIG            = ENVIROMENT.ALGOLIA_CREATE_ORDER_CONFIG;
	public static final String ALGOLIA_ETA_CONFIG                     = ENVIROMENT.ALGOLIA_ETA_CONFIG;
	public static final String TIME_OUT_CONFIG                     = ENVIROMENT.TIME_OUT_CONFIG;
	public static final String ALGOLIA_SCAN_AND_GO_PUSH_NOTIFICATION  = ENVIROMENT.ALGOLIA_SCAN_AND_GO_PUSH_NOTIFICATION;
	public static final String ALGOLIA_SCAN_AND_GO_PUSH_REGISTERED_ORDER = ENVIROMENT.ALGOLIA_SCAN_AND_GO_PUSH_REGISTERED_ORDER;
	public static final String ALGOLIA_MESSAGE_ITEMS_NOT_BILLED          = ENVIROMENT.ALGOLIA_MESSAGE_ITEMS_NOT_BILLED;
	public static final String ALGOLIA_DELIVERY_FAST				    = ENVIROMENT.ALGOLIA_DELIVERY_FAST;
	public static final String ALGOLIA_EXCLUDE_STORES_CREATE_ORDER	    = ENVIROMENT.ALGOLIA_EXCLUDE_STORES_CREATE_ORDER;
	public static final String ALGOLIA_TIME_FINALIZE_ORDERS			    = ENVIROMENT.ALGOLIA_TIME_FINALIZE_ORDERS;
	public static final String ALGOLIA_HOME_CONFIG			   			= ENVIROMENT.ALGOLIA_HOME_CONFIG;
	public static final String ALGOLIA_HOME_V2_CONFIG			   		= ENVIROMENT.ALGOLIA_HOME_V2_CONFIG;
	public static final String ALGOLIA_GEO_GRIDS			   		    = ENVIROMENT.ALGOLIA_GEO_GRIDS;
	public static final String ALGOLIA_LANDING_PAGES			   		= ENVIROMENT.ALGOLIA_LANDING_PAGES;
	public static final String ALGOLIA_PRODUCT_DETAIL			   		= ENVIROMENT.ALGOLIA_PRODUCT_DETAIL;
	public static final String ALGOLIA_AUTOCOMPLETE_CONFIG			   	= ENVIROMENT.ALGOLIA_AUTOCOMPLETE_CONFIG;
	public static final String ALGOLIA_HOME_DEFAULT_BANNERS			   	= ENVIROMENT.ALGOLIA_HOME_DEAFULT_BANNERS;
	public static final String ALGOLIA_USERS_CALL_CENTER			    = ENVIROMENT.ALGOLIA_USERS_CALL_CENTER;
	public static final String ALGOLIA_PASSWORD_INCORRECT			   	= ENVIROMENT.ALGOLIA_PASSWORD_INCORRECT;
	public static final String ALGOLIA_CONFIG_LOGIN_MESSAGE			   	= ENVIROMENT.ALGOLIA_CONFIG_LOGIN_MESSAGE;
	public static final String ALGOLIA_LOGIN_EMAIL_CONFIG           	= ENVIROMENT.ALGOLIA_LOGIN_EMAIL_CONFIG;
	public static final String ALGOLIA_DATA_AUTOCOMPLETE     			= ENVIROMENT.ALGOLIA_DATA_AUTOCOMPLETE;
	public static final String ALGOLIA_DATA_GEOCODING     			    = ENVIROMENT.ALGOLIA_DATA_GEOCODING;
	public static final String ALGOLIA_CONFIG_ITEM_OFFER_POPUP3X2		= ENVIROMENT.ALGOLIA_CONFIG_ITEM_OFFER_POPUP3X2;
	public static final String ALGOLIA_CONFIG_ITEM_OFFER_POPUP2X1		= ENVIROMENT.ALGOLIA_CONFIG_ITEM_OFFER_POPUP2X1;
	public static final String ALGOLIA_LANDING_PAGES_PROVIDER           = ENVIROMENT.ALGOLIA_LANDING_PAGES_PROVIDER;
	public static final String ALGOLIA_LANDING_PROVIDERS_AND_ACTIVE    	= ENVIROMENT.ALGOLIA_LANDING_PROVIDERS_AND_ACTIVE;
	public static final String ALGOLIA_CHARGE_ORDER_ACTIVE    			= ENVIROMENT.ALGOLIA_CHARGE_ORDER_ACTIVE;
	public static final String ALGOLIA_PRODUCTS_SCAN_AND_GO     	  	= ENVIROMENT.ALGOLIA_PRODUCTS_SCAN_AND_GO;
	public static final String ALGOLIA_APPS_URL_DEPARTMENTS            	= ENVIROMENT.ALGOLIA_APPS_URL_DEPARTMENTS;
	public static final String ALGOLIA_FTD_PRIME_CONFIG            	= ENVIROMENT.ALGOLIA_FTD_PRIME_CONFIG;
	public static final String ALGOLIA_APPS_VERSION_CONFIG 				= ENVIROMENT.ALGOLIA_APPS_VERSION_CONFIG;
	public static final String ALGOLIA_SECURITY_WEB_CONFIG				= ENVIROMENT.ALGOLIA_SECURITY_WEB_CONFIG;
	public static final String ALGOLIA_FILTERS_CONFIG					= ENVIROMENT.ALGOLIA_FILTERS_CONFIG;
	public static final String ALGOLIA_TIPS_CONFIG						= ENVIROMENT.ALGOLIA_TIPS_CONFIG;

	public static final String CONFIG_EXPLO_STORE						= ENVIROMENT.CONFIG_EXPLO_STORE;
	public static final String ALGOLIA_NOT_ALLOWED_TIPS					= ENVIROMENT.ALGOLIA_NOT_ALLOWED_TIPS;
	public static final String ALGOLIA_FLAG_REGISTRY                    = ENVIROMENT.ALGOLIA_FLAG_REGISTRY;
	public static final String ALGOLIA_COUPON_FILTERS                   = ENVIROMENT.ALGOLIA_COUPONS_FILTER;
	public static final String ALGOLIA_FREE_DELIVERY                    =ENVIROMENT.ALGOLIA_FREE_DELIVERY;
	public static final String ALGOLIA_SMS_MESSAGGES                  = ENVIROMENT.ALGOLIA_SMS_MESSAGGES_CONFIG ;
	public static final String ALGOLIA_ORDER_MESSAGES                   = ENVIROMENT.ALGOLIA_ORDER_MESSAGES;
	public static final String ALGOLIA_CARRUSEL_RECOMMEND               = ENVIROMENT.ALGOLIA_CARRUSEL_RECOMMEND;
	public static final String ALGOLIA_PHOTO_SLURP_CONFIG               = ENVIROMENT.ALGOLIA_PHOTO_SLURP_CONFIG;
	public static final String ALGOLIA_RECOMMEND_CONFIG               = ENVIROMENT.ALGOLIA_RECOMMEND_CONFIG;
	public static final String MESSAGE_VALIDATE_COUPON_CONFIG               = ENVIROMENT.MESSAGE_VALIDATE_COUPON_CONFIG;
	public static final String ALGOLIA_BANNER_PRIME            = ENVIROMENT.ALGOLIA_BANNER_PRIME;

	public static final String ALGOLIA_TALON_ONE           = ENVIROMENT.ALGOLIA_TALON_ONE;
	public static final String ALGOLIA_PETALO_TALON_ONE           = ENVIROMENT.ALGOLIA_PETALO_TALON_ONE;

	public static final String ALGOLIA_MAIN_CITIES = ENVIROMENT.ALGOLIA_MAIN_CITIES;


	public static final String ALGOLIA_REMINDERS   		       = "reminders_braze_col";

	/** Growthbook keys */

	public static final String GB_KEY_STORES_OPTIMALROUTE_CO = "stores-optimalroute-co" ;

	public static final String GB_KEY_TIPS_CONFIG_CO = "tips-config-co" ;

	/**URL CallCenterWS */
	public static final String URL_LOGIN_EMPLOYER                    = IP_BASE + Enviroment.URL_LOGIN_EMPLOYER;

	public static final String ALGOLIA_RATE_CONFIG_LIMIT              = ENVIROMENT.ALGOLIA_RATE_CONFIG_LIMIT;


	// opticas config

	public static final String ALGOLIA_OPTICAL_PRODUCTS     		  = ENVIROMENT.ALGOLIA_OPTICAL_PRODUCTS;

	public static final String OPTICS_ADDITIONAL_INFORMATION_CONFIG    = ENVIROMENT.OPTICS_ADDITIONAL_INFORMATION_CONFIG;

	public static final String PARAMETERS_LABELS_OPTICS    = ENVIROMENT.PARAMETERS_LABELS_OPTICS;

	public static final String MESSAGE_CONFIG_OPTICS    = ENVIROMENT.MESSAGE_CONFIG_OPTICS;

	public static final String MESSAGE_CONFIG_OPTICS_APPS    = ENVIROMENT.MESSAGE_CONFIG_OPTICS_APPS;

	public static final String OPTICS_CONFIG_DELIVERY_TIME    = ENVIROMENT.OPTICS_CONFIG_DELIVERY_TIME;

	/*growthBook */
	public static final String GB_CONFIG_GOOGLE_GEO_REFERENCING_CO    = ENVIROMENT.GB_CONFIG_GOOGLE_GEO_REFERENCING_CO;
	public static final String FEATURE_MARKETPLACE_ACTIVE    = ENVIROMENT.FEATURE_MARKETPLACE_ACTIVE;

	public static final String CACHE_TIME_SETTINGS    = ENVIROMENT.CACHE_TIME_SETTINGS;
	public static final String GB_KEY_DELIVERY_TYPE_TIME= ENVIROMENT.GB_KEY_DELIVERY_TYPE_TIME;

	/** URL DeliveryWS */

	/** No es posible su migracion debido a  **/
	public static final String URL_SEND_ORDER_TO_SIM              	   = IP_BASE + Enviroment.URL_SEND_ORDER_TO_SIM;
	public static final String URL_SIM_PING 						   = IP_BASE + Enviroment.URL_SIM_PING;
	public static final String URL_SIM_CREATE_FULFILLMENT_ORDER_DETAIL = IP_BASE + Enviroment.URL_SIM_CREATE_FULFILLMENT_ORDER_DETAIL;
	public static final String URL_RMS_PING 						   = IP_BASE + Enviroment.URL_RMS_PING;
	public static final String URL_RMS_CREATE_FULFIL_ORD_COL_DESC	   = IP_BASE + Enviroment.URL_RMS_CREATE_FULFIL_ORD_COL_DESC;

	/** Support Methods  */
	public static final String URL_SEND_SMS   = ENVIROMENT.URL_SEND_SMS;
	public static final String URL_SEND_EMAIL = ENVIROMENT.URL_SEND_EMAIL;

	/** Google oauth2 */
	public static final String URL_GOOGLE_AUTH = ENVIROMENT.URL_GOOGLE_AUTH;

	/** Monitor */
	//public static final String URL_ITEM_BARCODE                = IP_BASE + ENVIROMENT.URL_ITEM_BARCODE;
	//public static final String URL_ITEM_ID                     = IP_BASE + ENVIROMENT.URL_ITEM_ID;
	//public static final String URL_GET_ITEM_SUBSTITUTES        = IP_BASE + ENVIROMENT.URL_GET_ITEM_SUBSTITUTES;

	//public static final String URL_UPDATE_ORDER                = IP_BASE + ENVIROMENT.URL_UPDATE_ORDER;
	//public static final String URL_UPDATE_PAYMENT_METHOD_ORDER = IP_BASE + ENVIROMENT.URL_UPDATE_PAYMENT_METHOD_ORDER;

	public static final String URL_GET_ORDERS                            = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS;
	public static final String URL_GET_DETAIL_ORDER                      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_DETAIL_ORDER;
	public static final String URL_VALIDATE_BILL_ORDER                   = IP_BASE_MONITOR + ENVIROMENT.URL_VALIDATE_BILL_ORDER;
	public static final String URL_CANCEL_ORDER                          = IP_BASE_MONITOR + ENVIROMENT.URL_CANCEL_ORDER;
	public static final String URL_VALIDATE_ORDER_TOKEN                  = IP_BASE_MONITOR + ENVIROMENT.URL_VALIDATE_ORDER_TOKEN;
	public static final String URL_SAVE_ORDER_OBSERVATION                = IP_BASE_MONITOR + ENVIROMENT.URL_SAVE_ORDER_OBSERVATION;
	public static final String URL_GET_ORDER_OBSERVATIONS                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_OBSERVATIONS;
	public static final String URL_LOGIN_MONITOR_USER                    = IP_BASE_MONITOR + ENVIROMENT.URL_LOGIN_MONITOR_USER;
	public static final String URL_VALIDATE_SESSION_TOKEN                = IP_BASE_MONITOR + ENVIROMENT.URL_VALIDATE_SESSION_TOKEN;
	public static final String URL_RECOVERY_PASSWORD_USER                = IP_BASE_MONITOR + ENVIROMENT.URL_RECOVERY_PASSWORD_USER;
	public static final String URL_CHANGE_PASSWORD_USER                  = IP_BASE_MONITOR + ENVIROMENT.URL_CHANGE_PASSWORD_USER;
	public static final String URL_CREATE_USER                           = IP_BASE_MONITOR + ENVIROMENT.URL_CREATE_USER;
	public static final String URL_EDIT_USER                             = IP_BASE_MONITOR + ENVIROMENT.URL_EDIT_USER;
	public static final String URL_DELETE_USER                           = IP_BASE_MONITOR + ENVIROMENT.URL_DELETE_USER;
	public static final String URL_GET_ROLS_MONITOR                      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ROLS_MONITOR;
	public static final String URL_GET_USERS_MONITOR                     = IP_BASE_MONITOR + ENVIROMENT.URL_GET_USERS_MONITOR;
	public static final String URL_SEARCH_ORDERS                         = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS;
	public static final String URL_SEARCH_ORDERS_PROVIDERS               = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS_PROVIDERS;
	public static final String URL_GET_ORDERS_1_5                        = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_1_5;
	public static final String URL_SEARCH_ORDERS_1_5                     = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS_1_5;
	public static final String URL_SAVE_ORDER_OBSERVATION_1_5            = IP_BASE_MONITOR + ENVIROMENT.URL_SAVE_ORDER_OBSERVATION_1_5;
	public static final String URL_GET_ORDER_OBSERVATIONS_1_5            = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_OBSERVATIONS_1_5;
	public static final String URL_GET_DETAIL_ORDER_1_5                  = IP_BASE_MONITOR + ENVIROMENT.URL_GET_DETAIL_ORDER_1_5;
	public static final String URL_CANCEL_ORDER_1_5                      = IP_BASE_MONITOR + ENVIROMENT.URL_CANCEL_ORDER_1_5;
	public static final String URL_REASSIGN_ORDER                        = IP_BASE_MONITOR + ENVIROMENT.URL_REASSIGN_ORDER;
	public static final String URL_REASSIGN_ORDER_1_5                    = IP_BASE_MONITOR + ENVIROMENT.URL_REASSIGN_ORDER_1_5;
	public static final String URL_GET_STORES_COURIER                    = IP_BASE_MONITOR + ENVIROMENT.URL_GET_STORES_COURIER;
	public static final String URL_GET_STORES_WITHOUT_COURIER            = IP_BASE_MONITOR + ENVIROMENT.URL_GET_STORES_WITHOUT_COURIER;
	public static final String URL_UPDATE_STORES_WITHOUT_COURIER         = IP_BASE_MONITOR + ENVIROMENT.URL_UPDATE_STORES_WITHOUT_COURIER;
	public static final String URL_UPDATE_STORES_COURIER                 = IP_BASE_MONITOR + ENVIROMENT.URL_UPDATE_STORES_COURIER;
	public static final String URL_GET_ORDER_QR_CODE                     = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_QR_CODE;
	public static final String URL_SEARCH_ID_ORDERS                      = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ID_ORDERS;
	public static final String URL_SEARCH_ID_ORDERS_1_5                  = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ID_ORDERS_1_5;
	public static final String URL_GET_ID_ORDERS                         = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS;
	public static final String URL_GET_ID_ORDERS_1_5                     = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_1_5;
	public static final String URL_GET_ID_ORDERS_PROGRAMMED              = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_PROGRAMMED;
	public static final String URL_GET_ID_ORDERS_PROVIDE                 = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_PROVIDE;
	public static final String URL_REPUSH_ORDER                          = IP_BASE_MONITOR + ENVIROMENT.URL_REPUSH_ORDER;
	public static final String URL_GET_ORDER_TICKET_STORE                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_TICKET_STORE;
	public static final String URL_GET_ORDER_PAYU_RESPONSE               = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_PAYU_RESPONSE;
	public static final String URL_MANAGER_ORDER                         = IP_BASE_MONITOR + ENVIROMENT.URL_MANAGER_ORDER;
	public static final String URL_MANAGER_ORDER_1_5                     = IP_BASE_MONITOR + ENVIROMENT.URL_MANAGER_ORDER_1_5;
	public static final String URL_GET_ID_ORDERS_1_5_MANAGERS            = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_1_5_MANAGERS;
	public static final String URL_GET_ID_ORDERS_MANAGERS                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_MANAGERS;
	public static final String URL_GET_ID_ORDERS_BILLED                  = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_BILLED;
	public static final String URL_MANAGER_ORDER_SUMARY                  = IP_BASE_MONITOR + ENVIROMENT.URL_MANAGER_ORDER_SUMARY;
	public static final String URL_GET_ORDERS_SUMARY_BY_TYPE             = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_SUMARY_BY_TYPE;
	public static final String URL_REASSIGN_ORDER_MANUAL                 = IP_BASE_MONITOR + ENVIROMENT.URL_REASSIGN_ORDER_MANUAL;
	public static final String URL_REASSIGN_ORDER_MANUAL_1_5             = IP_BASE_MONITOR + ENVIROMENT.URL_REASSIGN_ORDER_MANUAL_1_5;
	public static final String URL_FINALIZE_ORDER                        = IP_BASE_MONITOR + ENVIROMENT.URL_FINALIZE_ORDER;
	public static final String URL_FINALIZE_ORDER_1_5                    = IP_BASE_MONITOR + ENVIROMENT.URL_FINALIZE_ORDER_1_5;
	public static final String URL_COUNT_RESUME_ORDERS_2_0               = IP_BASE_MONITOR + ENVIROMENT.URL_COUNT_RESUME_ORDERS_2_0;
	public static final String URL_GET_ID_ORDERS_NO_EXPRESS              = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_NO_EXPRESS;
	public static final String URL_GET_ID_ORDERS_SS                      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_SS;
	public static final String URL_GET_ORDERS_ASSIGNED_MANUAL            = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_ASSIGNED_MANUAL;
	public static final String URL_GET_ORDERS_ASSIGNED_MANUAL_15         = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_ASSIGNED_MANUAL_15;
	public static final String URL_GET_DETAIL_ORDER_NO_EXPRESS           = IP_BASE_MONITOR + ENVIROMENT.URL_GET_DETAIL_ORDER_NO_EXPRESS;
	public static final String URL_GET_ORDER_CREDIT_NOTE_TICKET          = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_CREDIT_NOTE_TICKET;
	public static final String URL_MODIFY_STATUS_ORDER                   = IP_BASE_MONITOR + ENVIROMENT.URL_MODIFY_STATUS_ORDER;
	public static final String URL_ADD_ORDER_GUIDE                       = IP_BASE_MONITOR + ENVIROMENT.URL_ADD_ORDER_GUIDE;
	public static final String URL_INSERT_CLICK_WHATSAPP                 = IP_BASE_MONITOR + ENVIROMENT.URL_INSERT_CLICK_WHATSAPP;
	public static final String URL_GET_REPORT_MANAGAMENT                 = IP_BASE_MONITOR + ENVIROMENT.URL_GET_REPORT_MANAGAMENT;
	public static final String URL_GET_REPORT_MANAGAMENT_15              = IP_BASE_MONITOR + ENVIROMENT.URL_GET_REPORT_MANAGAMENT_15;
	public static final String URL_ADD_ORDER_SUMMARY                     = IP_BASE_MONITOR + ENVIROMENT.URL_ADD_ORDER_SUMMARY;
	public static final String URL_GET_POS_NUMBER_ORDER                  = IP_BASE_MONITOR + ENVIROMENT.URL_GET_POS_NUMBER_ORDER;
	public static final String URL_GET_ORDER_EVIDENCES                   = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_EVIDENCES;
	public static final String URL_GET_ORDER_EVIDENCES_15                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDER_EVIDENCES_15;
	public static final String URL_SEARCH_ORDERS_NO_EXPRESS              = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS_NO_EXPRESS;
	public static final String URL_GET_ORDERS_MESSENGER_ASSIGNED         = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_MESSENGER_ASSIGNED;
	public static final String URL_GET_ORDERS_MESSENGER_ASSIGNED_15      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_MESSENGER_ASSIGNED_15;
	public static final String URL_SEARCH_ID_ORDERS_PROVIDERS            = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ID_ORDERS_PROVIDERS;
	public static final String URL_SEARCH_ORDERS_REPORTS                 = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS_REPORTS;
	public static final String URL_GET_ID_ORDERS_CANCELLED               = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_CANCELLED;
	public static final String URL_GET_ID_ORDERS_1_5_CANCELLED           = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_1_5_CANCELLED;
	public static final String URL_GET_ORDERS_GLUED                      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_GLUED;
	public static final String URL_GET_ORDERS_1_5_GLUED                  = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_1_5_GLUED;
	public static final String URL_GET_IS_ORDER_REASSIGNED               = IP_BASE_MONITOR + ENVIROMENT.URL_GET_IS_ORDER_REASSIGNED;
	public static final String URL_GET_IS_ORDER_REASSIGNED_1_5           = IP_BASE_MONITOR + ENVIROMENT.URL_GET_IS_ORDER_REASSIGNED_1_5;
	public static final String URL_SEARCH_ORDERS_REPORTS_1_5             = IP_BASE_MONITOR + ENVIROMENT.URL_SEARCH_ORDERS_REPORTS_1_5;
	public static final String URL_ORDER_PROVIDER_MONITOR                = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_PROVIDER_MONITOR;
	public static final String URL_ORDER_STUCK_AVERAGE20                 = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_STUCK_AVERAGE20;
	public static final String URL_ORDER_STUCK_AVERAGE20_CITY            = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_STUCK_AVERAGE20_CITY;
	public static final String URL_ORDER_DELIVEY_AVERAGE20               = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_DELIVEY_AVERAGE20;
	public static final String URL_ORDER_DELIVEY_AVERAGE20_CITY          = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_DELIVEY_AVERAGE20_CITY;
	public static final String URL_ORDER_STUCK_AVERAGE15                 = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_STUCK_AVERAGE15;
	public static final String URL_ORDER_STUCK_AVERAGE15_CITY            = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_STUCK_AVERAGE15_CITY;
	public static final String URL_ORDER_DELIVEY_AVERAGE15               = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_DELIVEY_AVERAGE15;
	public static final String URL_ORDER_DELIVEY_AVERAGE15_CITY          = IP_BASE_MONITOR + ENVIROMENT.URL_ORDER_DELIVEY_AVERAGE15_CITY;
	public static final String URL_PUT_ORDERS_STUCK_AVERAGE              = IP_BASE_MONITOR + ENVIROMENT.URL_PUT_ORDERS_STUCK_AVERAGE;
	public static final String URL_PUT_ORDERS_STUCK_AVERAGE_CITY         = IP_BASE_MONITOR + ENVIROMENT.URL_PUT_ORDERS_STUCK_AVERAGE_CITY;
	public static final String URL_PUT_ORDERS_DELIVERY_TIME_AVERAGE      = IP_BASE_MONITOR + ENVIROMENT.URL_PUT_ORDERS_DELIVERY_TIME_AVERAGE;
	public static final String URL_PUT_ORDERS_DELIVERY_TIME_AVERAGE_CITY = IP_BASE_MONITOR + ENVIROMENT.URL_PUT_ORDERS_DELIVERY_TIME_AVERAGE_CITY;
	public static final String URL_GET_ORDERS_STUCK_AVERAGE              = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_STUCK_AVERAGE;
	public static final String URL_GET_ORDERS_STUCK_AVERAGE_CITY         = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_STUCK_AVERAGE_CITY;
	public static final String URL_GET_ORDERS_DELIVERY_TIME_AVERAGE      = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_DELIVERY_TIME_AVERAGE;
	public static final String URL_GET_ORDERS_DELIVERY_TIME_AVERAGE_CITY = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_DELIVERY_TIME_AVERAGE_CITY;
	public static final String URL_GET_ID_ORDERS_ISSUED20                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_ISSUED20;
	public static final String URL_GET_ID_ORDERS_ISSUED15                = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ID_ORDERS_ISSUED15;
	public static final String URL_GET_ORDERS_COODINATES20               = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_COODINATES20;
	public static final String URL_GET_ORDERS_COODINATES15               = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_COODINATES15;
	public static final String URL_ACTIVATE_ORDER_CANCELED               = IP_BASE_MONITOR + ENVIROMENT.URL_ACTIVATE_ORDER_CANCELED;
	public static final String URL_SAVE_ORDER_ACTIVATED_ASSOCIATION      = IP_BASE_MONITOR + ENVIROMENT.URL_SAVE_ORDER_ACTIVATED_ASSOCIATION;
	public static final String URL_GET_ORDERS_ACTIVATED_ASOCIATION       = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_ACTIVATED_ASOCIATION;
	public static final String URL_GET_ORDERS_CANCELED_ASOCIATION        = IP_BASE_MONITOR + ENVIROMENT.URL_GET_ORDERS_CANCELED_ASOCIATION;
	public static final String URL_UPDATE_ORDER_EXPRESS_PICKING_DATE     = IP_BASE_MONITOR + ENVIROMENT.URL_UPDATE_ORDER_EXPRESS_PICKING_DATE;
	public static final String URL_GET_EVIDENCES_ORDER20     			 = IP_BASE_MONITOR + ENVIROMENT.URL_GET_EVIDENCES_ORDER20;

	public static final String URL_PUSH_NOTIFICATION_MONITOR       = ENVIROMENT.URL_MONITOR_SERVER + "prueba/";
	public static final String URL_PUSH_NOTIFICATION_NEW_ORDER     = ENVIROMENT.URL_MONITOR_SERVER + "notificationOrder/";

	/** Https Methods */
	public final static String GET    = ENVIROMENT.GET;
	public final static String PUT    = ENVIROMENT.PUT;
	public final static String POST   = ENVIROMENT.POST;
	public final static String DELETE = ENVIROMENT.DELETE;

	/** Properties */
	public final static String CONTENT_TYPE_JSON = ENVIROMENT.CONTENT_TYPE_JSON;

	/** Errors  */
	public final static String NO_CONTENT      = ENVIROMENT.NO_CONTENT;
	public final static String BAD_REQUEST     = ENVIROMENT.BAD_REQUEST;
	public final static String SERVER_ERROR    = ENVIROMENT.SERVER_ERROR;
	public final static String DEFAULT         = ENVIROMENT.DEFAULT;
	public final static String SUCCESS_MESSAGE = ENVIROMENT.SUCCESS_MESSAGE;
	public final static String MESSAGE_DECLINED_FOR_ANTIFRAUD = "La transacción fue rechazada";
	public final static String MESSAGE_DECLINED_FOR_FOUNDS = "La cuenta no tenía fondos suficientes";

	/** Ciudades Principales */
	//public final static String MAIN_CITIES = ENVIROMENT.MAIN_CITIES;

        // Validate Stock CORE Api

    // public static final String URL_VALIDATE_STOCK_API = "DeliveryWS/v1/order/validateStockRoute";

	public static final String URL_GET_ID_ORDERS_2_0_JSON          = IP_BASE_MONITOR + "MonitorWS/v1/getOrders20JSON";
	public static final String URL_GET_ID_ORDERS_1_5_JSON          = IP_BASE_MONITOR + "MonitorWS/v1/getOrders15JSON";
	public static final String URL_UPDATE_ORDERS_2_0_IN_TEMP       = IP_BASE_MONITOR + "MonitorWS/v1/putOrders20InTemporalyTable";
	public static final String URL_UPDATE_ORDERS_1_5_IN_TEMP       = IP_BASE_MONITOR + "MonitorWS/v1/putOrders15InTemporalyTable";
	public static final String URL_SEARCH_ID_ORDERS_REPORT_2_0     = IP_BASE_MONITOR + "MonitorWS/v1/searchIdOrdersReports20";
	public static final String URL_SEARCH_ID_ORDERS_REPORT_1_5     = IP_BASE_MONITOR + "MonitorWS/v1/searchIdOrdersReports15";
	public static final String URL_UPDATE_USER_TOKEN_FIREBASE      = IP_BASE_MONITOR + "MonitorWS/v1/updateTokenFirebase";
	public static final String URL_ADD_ORDER_GUIDE_PROVIDER        = IP_BASE_MONITOR + "MonitorWS/v1/addOrderGuideProvider";
	public static final String URL_MODIFY_STATUS_ORDER_PROVIDER    = IP_BASE_MONITOR + "MonitorWS/v1/modifyOrderStatus20Provider";

	//SMS HABLAME
	public final static String URL_SEND_SMS_HABLAME = "https://api.hablame.co/sms/envio/?" + "api=" + Constants.SMS_API + "&cliente=" + Constants.SMS_CLIENT;





  public static final String URL_UPDATE_ORDERS_PROVIDER_IN_TEMP   = IP_BASE_MONITOR + "MonitorWS/v1/putOrdersProviderInTemporalyTable";
  public static final String URL_UPDATE_ORDERS_NO_EXPRESS_IN_TEMP = IP_BASE_MONITOR + "MonitorWS/v1/putOrdersNoExpressInTemporalyTable";
  public static final String URL_GET_ID_ORDERS_CANCELLED_PROVIDER = IP_BASE_MONITOR + "MonitorWS/v1/getIdCanceledOrderForProvider";
  public static final String URL_GET_ID_ORDERS_CANCELLED_NO_EXPRESS = IP_BASE_MONITOR + "MonitorWS/v1/getIdCanceledOrdersNoExpress";
  public static final String URL_GET_ID_ORDERS_CANCELLED_SUBSCRIPTION = IP_BASE_MONITOR + "MonitorWS/v1/getIdCanceledOrdersSubscription";
  public static final String URL_GET_ID_ORDERS_INCOMPLETES_NO_EXPRESS = IP_BASE_MONITOR + "MonitorWS/v1/getIdIncompletedOrdersNoExpress";
  public static final String URL_GET_DETAIL_ORDER_INCOMPLETED_NO_EXPRESS = IP_BASE_MONITOR + "MonitorWS/v1/getOrderDetailNoExpressIncompleted";
  public static final String URL_INSERT_ITEM_ORDER_INCOMPLETED    = IP_BASE_MONITOR + "MonitorWS/v1/insertItemOrderIncomplete";
  public static final String URL_SEND_MAIL_NO_EXPRESS   = IP_BASE_MONITOR + "MonitorWS/v1/sendMailNoExpress";

  //MONITOR NOTIFICATION SERVER
  private static final String URL_MONITOR_SERVER = "https://monitor-server-dot-web-farmatodo.appspot.com/";

  public static final String URL_TALON_ONE_TRACK_EVENT_ITEM_PURCHASED= ENVIROMENT.API_GATEWAY + ENVIROMENT.URL_TALON_ONE_TRACK_EVENT_ITEM_PURCHASED;
  public static final String FIREBASE_AUTHENTICATION_EMAIL = ENVIROMENT.FIREBASE_AUTHENTICATION_EMAIL;

  public static final String FIREBASE_AUTHENTICATION_PASSWORD = ENVIROMENT.FIREBASE_AUTHENTICATION_PASSWORD;

  public static final String FIREBASE_API_KEY = ENVIROMENT.FIREBASE_API_KEY;

  public static final String URL_UTILITIES_DIRECT = ENVIROMENT.NEST_UTILITIES_DIRECT;

	/** Talon One **/
	public static final String URL_TALON_ONE = ENVIROMENT.URL_TALON_ONE;
	public static final String URL_TALON_ONE_TRACK_EVENT= ENVIROMENT.API_GATEWAY + ENVIROMENT.URL_TALON_ONE_TRACK_EVENT;
	public static final String URL_TALON_ONE_CUSTOMER_SESSION				= ENVIROMENT.API_GATEWAY + ENVIROMENT.URL_TALON_ONE_CUSTOMER_SESSION;
	public static final String URL_TALON_ONE_RETRIEVE_DEDUCT_DISCOUNT			= ENVIROMENT.URL_TALON_ONE + ENVIROMENT.URL_TALON_ONE_RETRIEVE_DEDUCT_DISCOUNT;
  	//flag send errors by text sms
    public static final boolean SEND_ERROR_BY_TEXT_SMS = Enviroment.SEND_ERROR_BY_TEXT_SMS;

	public static final String URL_OMS_RELEASE_ACTIVE_ORDERS = Enviroment.API_GATEWAY + "oms/v1/order/release/orders/active";

	public static final String URL_OMS_RELEASE_PREVIOUS_ORDERS = Enviroment.API_GATEWAY + "oms/v1/order/release/orders/previous";

	public static final String URL_KUSTOMER = ENVIROMENT.URL_KUSTOMER;


	public static HttpURLConnection getConnection(String requestMethod, String urlString) throws IOException {
    URL url = new URL(urlString);
    HttpURLConnection httpURLConnection = (HttpURLConnection) url.openConnection();
    httpURLConnection.setRequestProperty("Accept-Charset", "UTF-8");
    httpURLConnection.setRequestProperty("Content-Type", "application/json");
    httpURLConnection.setRequestProperty("Accept", "application/json");
    httpURLConnection.setDoInput(true);
    httpURLConnection.setDoOutput(true);
    httpURLConnection.setRequestMethod(requestMethod);
    httpURLConnection.setReadTimeout(100000);
    httpURLConnection.setConnectTimeout(100000);
    return httpURLConnection;
  }
}