// Code generated by MockGen. DO NOT EDIT.
// Source: carousel.go
//
// Generated by this command:
//
//	mockgen -source=carousel.go -destination=../../../../../test/mocks/carousel/domain/ports/in/carousel_mock.go
//

// Package mock_in is a generated GoMock package.
package mock_in

import (
	model "ftd-td-home-read-services/internal/carousel/domain/model"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockCarousel is a mock of Carousel interface.
type MockCarousel struct {
	ctrl     *gomock.Controller
	recorder *MockCarouselMockRecorder
	isgomock struct{}
}

// MockCarouselMockRecorder is the mock recorder for MockCarousel.
type MockCarouselMockRecorder struct {
	mock *MockCarousel
}

// NewMockCarousel creates a new mock instance.
func NewMockCarousel(ctrl *gomock.Controller) *MockCarousel {
	mock := &MockCarousel{ctrl: ctrl}
	mock.recorder = &MockCarouselMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarousel) EXPECT() *MockCarouselMockRecorder {
	return m.recorder
}

// GetSuggested mocks base method.
func (m *MockCarousel) GetSuggested(c *gin.Context, countryID string, storeGroupID int64) ([]model.Suggested, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuggested", c, countryID, storeGroupID)
	ret0, _ := ret[0].([]model.Suggested)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuggested indicates an expected call of GetSuggested.
func (mr *MockCarouselMockRecorder) GetSuggested(c, countryID, storeGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuggested", reflect.TypeOf((*MockCarousel)(nil).GetSuggested), c, countryID, storeGroupID)
}
