package com.imaginamos.farmatodo.model.order;

public enum Bck3EventResponseCode {
    OK,
    NO_CONTENT,
    BAD_REQUEST,
    BUSSINESS_ERROR,
    APPLICATION_ERROR,
    UNAUTHORIZED,
    CONFLICT,
    INVALID_TOKEN,
    TOKEN_REQUIRED,
    TOKEN_EXPIRED,
    INVALID_CLIENT_ID,
    INVALID_CLIENT_SECRET,
    PAYMENT_APROVED,
    PAYMENT_DECLINED,
    PAYMENT_REPEAT_TRANSACTION,
    PAYMENT_DAILY_ATTEMPTS_EXCEEDED,
    PAYMENT_DUPLICATED,
    PAYMENT_ERROR,
    REJECTED,
    DUPLICATED,
    ERROR,
    CREATED;
}
