package com.imaginamos.farmatodo.model.dto

enum class ComponentTypeEnum

(var componentType: String?) {
    BANNER("BANNER"),
    SQUARE_TWO_BANNER("SQUARE_TWO_BANNER"),
    BANNER_LOGIN("BANNER_LOGIN"),
    MIN_BANNER_LEFT("MIN_BANNER_LEFT"),
    SMALL_BANNER("SMALL_BANNER"),
    RECT_BANNER("RECT_BANNER"),
    TWO_RECT_BANNER("TWO_RECT_BANNER"),
    TOW_RECT_BANNER("TOW_RECT_BANNER"),
    SHORTCUT_BANNER("SHORTCUT_BANNER"),
    BANNER_LEFT_ADVERTISING("BANNER_LEFT_ADVERTISING"),
    BANNER_RIGHT_ADVERTISING("BANNER_LEFT_ADVERTISING"),
    STATIC_BANNER("STATIC_BANNER"),
    TRACKING_INFO("TRACKING_INFO"),
    HTML_LABEL("HTML_LABEL"),
    SEARCH_FIELD("SEARCH_FIELD"),
    THIN_BANNER("THIN_BANNER"),
    SQUARE_BANNER("SQUARE_BANNER"),
    CIRCLE_BANNER("CIRCLE_BANNER"),
    WEB_DIRECT_BANNER("WEB_DIRECT_BANNER"),
    ITEM_LIST("ITEM_LIST"),
    BRAZE_CAROUSEL("BRAZE_CAROUSEL"),
    MAIN_ITEM("MAIN_ITEM"),
    ITEM_SEO("ITEM_SEO"),
    ITEM_HTML("ITEM_HTML"),
    BAZAARVOICE("BAZAARVOICE"),
    SMALL_ITEM_LIST("SMALL_ITEM_LIST"),
    GRID_BLOG_LIST("GRID_BLOG_LIST"),
    ITEM_LIST_TWO_ROWS("ITEM_LIST_TWO_ROWS"),
    VIDEO_LIST("VIDEO_LIST"),
    FAVORITES_ITEMS_LIST("FAVORITES_ITEMS_LIST"),
    GRID_ITEM_LIST("GRID_ITEM_LIST"),
    FLASH_OFFERS("FLASH_OFFERS"),
    PHOTOSLURP("PHOTOSLURP"),
    PHOTOSLURPGRID("PHOTOSLURPGRID"),
    PRIME_SAVINGS("PRIME_SAVINGS");

    override fun toString(): String {
        return "HomeComponentTypeEnum{" +
                "componentType='" + componentType + '\''.toString() +
                '}'.toString()
    }
}
