// Code generated by MockGen. DO NOT EDIT.
// Source: same_brand.go
//
// Generated by this command:
//
//	mockgen -source=same_brand.go -destination=../../../../../test/mocks/same-brand/infra/api/groups/same_brand_mock.go
//

// Package mock_groups is a generated GoMock package.
package mock_groups

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockSameBrand is a mock of SameBrand interface.
type MockSameBrand struct {
	ctrl     *gomock.Controller
	recorder *MockSameBrandMockRecorder
}

// MockSameBrandMockRecorder is the mock recorder for MockSameBrand.
type MockSameBrandMockRecorder struct {
	mock *MockSameBrand
}

// NewMockSameBrand creates a new mock instance.
func NewMockSameBrand(ctrl *gomock.Controller) *MockSameBrand {
	mock := &MockSameBrand{ctrl: ctrl}
	mock.recorder = &MockSameBrandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSameBrand) EXPECT() *MockSameBrandMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockSameBrand) Source(rg *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Source", rg)
}

// Source indicates an expected call of Source.
func (mr *MockSameBrandMockRecorder) Source(rg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockSameBrand)(nil).Source), rg)
}
