// Code generated by MockGen. DO NOT EDIT.
// Source: carousel.go
//
// Generated by this command:
//
//	mockgen -source=carousel.go -destination=../../../../../test/mocks/carousel/infra/api/groups/carousel_mock.go
//

// Package mock_groups is a generated GoMock package.
package mock_groups

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockCarousel is a mock of Carousel interface.
type MockCarousel struct {
	ctrl     *gomock.Controller
	recorder *MockCarouselMockRecorder
	isgomock struct{}
}

// MockCarouselMockRecorder is the mock recorder for MockCarousel.
type MockCarouselMockRecorder struct {
	mock *MockCarousel
}

// NewMockCarousel creates a new mock instance.
func NewMockCarousel(ctrl *gomock.Controller) *MockCarousel {
	mock := &MockCarousel{ctrl: ctrl}
	mock.recorder = &MockCarouselMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarousel) EXPECT() *MockCarouselMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockCarousel) Source(rg *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Source", rg)
}

// Source indicates an expected call of Source.
func (mr *MockCarouselMockRecorder) Source(rg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockCarousel)(nil).Source), rg)
}
