// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infra/api/handler/user/userHandler.go
//
// Generated by this command:
//
//	mockgen -source=internal/infra/api/handler/user/userHandler.go -destination=test/mocks/infra/api/handler/userHandler_mock.go -package=mocks_handler
//

// Package mocks_handler is a generated GoMock package.
package mocks_handler

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockUserHandlerInterface is a mock of UserHandlerInterface interface.
type MockUserHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockUserHandlerInterfaceMockRecorder is the mock recorder for MockUserHandlerInterface.
type MockUserHandlerInterfaceMockRecorder struct {
	mock *MockUserHandlerInterface
}

// NewMockUserHandlerInterface creates a new mock instance.
func NewMockUserHandlerInterface(ctrl *gomock.Controller) *MockUserHandlerInterface {
	mock := &MockUserHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockUserHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserHandlerInterface) EXPECT() *MockUserHandlerInterfaceMockRecorder {
	return m.recorder
}

// GetUsers mocks base method.
func (m *MockUserHandlerInterface) GetUsers(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUsers", c)
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUserHandlerInterfaceMockRecorder) GetUsers(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUserHandlerInterface)(nil).GetUsers), c)
}
