// Code generated by MockGen. DO NOT EDIT.
// Source: banner.go
//
// Generated by this command:
//
//	mockgen -source=banner.go -destination=../../../../../test/mocks/banner/infra/api/groups/banner_mock.go
//

// Package mock_groups is a generated GoMock package.
package mock_groups

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockBannerGroup is a mock of BannerGroup interface.
type MockBannerGroup struct {
	ctrl     *gomock.Controller
	recorder *MockBannerGroupMockRecorder
	isgomock struct{}
}

// MockBannerGroupMockRecorder is the mock recorder for MockBannerGroup.
type MockBannerGroupMockRecorder struct {
	mock *MockBannerGroup
}

// NewMockBannerGroup creates a new mock instance.
func NewMockBannerGroup(ctrl *gomock.Controller) *MockBannerGroup {
	mock := &MockBannerGroup{ctrl: ctrl}
	mock.recorder = &MockBannerGroupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBannerGroup) EXPECT() *MockBannerGroupMockRecorder {
	return m.recorder
}

// Source mocks base method.
func (m *MockBannerGroup) Source(rg *gin.RouterGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Source", rg)
}

// Source indicates an expected call of Source.
func (mr *MockBannerGroupMockRecorder) Source(rg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockBannerGroup)(nil).Source), rg)
}
