package com.imaginamos.farmatodo.backend.util;

import java.io.Serializable;

public class CustomStringUtil implements Serializable {

    public static final String formatItemUrl(String texto) {
        if (texto == null) {
            return "";
        }
        return texto.toLowerCase()
                .trim()
                .replaceAll("[\\u00A0\\u2007\\u202F]+", "")
                .replace("´","")
                .replace(" ", "-")
                .replace("  ", " ")
                .replace("   ", " ")
                .replace("    ", " ")
                .replace("     ", " ")
                .replace("--", "-")
                .replace('á','a')
                .replace('é','e')
                .replace('í','i')
                .replace('ó','o')
                .replace('ú','u')
                .replace('ñ','n')
                .replace('ü','u')
                .replace("/","")
                .replace(".","")
                .replace("%","")
                .replace("'","")
                .replace("#","")
                .replace("!","")
                .replace("&","")
                .replace("(","")
                .replace(")","")
                .replace("*","")
                .replace(".","")
                .replace(":","")
                .replace(";","")
                .replace("<","")
                .replace("?","")
                .replace("+","")
                .replace("@","")
                .replace("\\","")
                .replace("^","")
                .replace("_","")
                .replace("{","")
                .replace("}","")
                .replace("|","")
                .replace("$","")
                .replace(",","")
                .replace("$","")
                .replace("~","")
                .replace("!","")
                .replace("#","")
                .replace("$","")
                .replace("%","")
                .replace("&","")
                .replace("'","")
                .replace("(","")
                .replace(")","")
                .replace("*","")
                .replace("+","")
                .replace(",","")
                .replace("-","")
                .replace(".","")
                .replace("/","")
                .replace(":","")
                .replace(";","")
                .replace("<","")
                .replace("=","")
                .replace(">","")
                .replace("?","")
                .replace("[","")
                .replace("]","")
                .replace("^","")
                .replace("_","")
                .replace("{","")
                .replace("|","")
                .replace("}","")
                .replace("~","")
                .replace("¡","")
                .replace("¢","")
                .replace("£","")
                .replace("¤","")
                .replace("¥","")
                .replace("¦","")
                .replace("§","")
                .replace("¨","")
                .replace("©","")
                .replace("ª","")
                .replace("«","")
                .replace("¬","")
                .replace("®","")
                .replace("¯","")
                .replace("°","")
                .replace("±","")
                .replace("²","")
                .replace("³","")
                .replace("´","")
                .replace("µ","")
                .replace("¶","")
                .replace("·","")
                .replace("¸","")
                .replace("¹","")
                .replace("º","")
                .replace("»","")
                .replace("¼","")
                .replace("½","")
                .replace("¾","")
                .replace("¿","")
                .replace("À","")
                .replace("Á","")
                .replace("Â","")
                .replace("Ã","")
                .replace("Ä","")
                .replace("Å","")
                .replace("Æ","")
                .replace("Ç","")
                .replace("Î","")
                .replace("Ï","")
                .replace("Ð","")
                .replace("Ô","")
                .replace("Õ","")
                .replace("Ö","")
                .replace("×","")
                .replace("Ø","")
                .replace("Ù","")
                .replace("Þ","")
                .replace("ß","")
                .replace("à","")
                .replace("â","")
                .replace("ã","")
                .replace("ä","")
                .replace("å","")
                .replace("æ","")
                .replace("ç","")
                .replace("ê","")
                .replace("ë","")
                .replace("ì","")
                .replace("î","")
                .replace("ï","")
                .replace("ð","")
                .replace("ô","")
                .replace("õ","")
                .replace("ö","")
                .replace("÷","")
                .replace("ø","")
                .replace("ù","")
                .replace("û","")
                .replace("ü","")
                .replace("ý","")
                .replace("þ","")
                .replace("ÿ","");
    }

}
