package com.imaginamos.farmatodo.model.user;

import com.google.api.server.spi.config.AnnotationBoolean;
import com.google.api.server.spi.config.ApiResourceProperty;
import com.googlecode.objectify.Ref;
import com.googlecode.objectify.annotation.Entity;
import com.googlecode.objectify.annotation.Id;
import com.googlecode.objectify.annotation.Index;
import com.googlecode.objectify.annotation.Parent;

/**
 * Created by mileniopc on 11/10/16.
 * Property of Imaginamos.
 */

@Entity
public class DeviceRegistry {
  //User to which the device is associated
  @ApiResourceProperty(ignored = AnnotationBoolean.TRUE)
  @Parent
  private Ref<User> owner;
  //Unique identifier, generated by UUID
  @ApiResourceProperty(ignored = AnnotationBoolean.TRUE)
  @Id
  private String idDeviceRegistry;
  //Device token
  @Index
  private String deviceId;
  @Index
  private String firebaseTokenDevice;
  @Index
  private boolean available;
  private String type;

  public Ref<User> getOwner() {
    return owner;
  }

  public void setOwner(Ref<User> owner) {
    this.owner = owner;
  }

  public String getIdDeviceRegistry() {
    return idDeviceRegistry;
  }

  public void setIdDeviceRegistry(String idDeviceRegistry) {
    this.idDeviceRegistry = idDeviceRegistry;
  }

  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public String getFirebaseTokenDevice() {
    return firebaseTokenDevice;
  }

  public void setFirebaseTokenDevice(String firebaseTokenDevice) {
    this.firebaseTokenDevice = firebaseTokenDevice;
  }

  public boolean isAvailable() {
    return available;
  }

  public void setAvailable(boolean available) {
    this.available = available;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }
}
